sudo: false
dist: trusty

language: cpp
compiler: gcc

# caching of the build dir (which is large, so large timeout (3 minute default))
cache:
  timeout: 1000
  directories:
  - ../root_build  # the build directory
  - ../deps        # cmake
  - files          # testing downloads some files to the git repo dir

# following http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
# updated with https://stackoverflow.com/a/49412522/1199693 for trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ninja-build
      - gcc-7
      - g++-7
      - libxpm-dev
      - libgsl0-dev
      - libfftw3-dev
      - libafterimage-dev
      - libftgl-dev
      - libgl2ps-dev
      - libglew-dev
      - liblzma-dev

# following http://stackoverflow.com/a/33203355/1199693 and https://github.com/Microsoft/GSL/blob/master/.travis.yml
before_install:
  - |
    DEPS_DIR="${TRAVIS_BUILD_DIR}/../deps"
    mkdir -p "${DEPS_DIR}"

install:
  - mkdir -p "${TRAVIS_BUILD_DIR}"/../root_build

  include:
    - env: TOOL=clang-format
      script: &format_script
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then .ci/format_script.sh; fi

    - env: TOOL=clang-tidy-analyzer
      before_script: &copy_headers
        - echo "Copying and generating header files."
        - echo -en "travis_fold:start:install.headers"
        - .ci/copy_headers.sh
        - echo -en 'travis_fold:end:install.headers\\r'

      script: &tidy_script
        - |
          if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            .ci/tidy_script.sh
          fi

    - env: TOOL=clang-tidy-modernize
      before_script: *copy_headers
      script: *tidy_script

    - env: TOOL=minuit2-standalone
      script: cd math/minuit2 && .ci/make_and_test.sh

  allow_failures:
    # clang-tidy-modernize is still experimental
    - env: TOOL=clang-tidy-modernize
    # a lot of code doesn't follow clang-format yet
    - env: TOOL=clang-format


# This will never run since there is not a clang-tidy only TOOL
#  elif [[ "$TRAVIS_EVENT_TYPE" = "cron" ]] && [[ $TOOL == 'clang-tidy' ]]; then
#    # We need to ignore our vendor drops.
#    FILES_REGEX='^.*root\/(?!interpreter\/|core\/clib)'
#
#    echo "Running clang-tidy-3.9 against branch $TRAVIS_BRANCH."
#    echo "run-clang-tidy-3.9.py -j4 -clang-tidy-binary $(which clang-tidy-3.9) -checks=-*,clang-analyzer-* $FILES_REGEX"
#    run-clang-tidy-3.9.py -j4 -clang-tidy-binary $(which clang-tidy-3.9) -checks=-*,clang-analyzer-* $FILES_REGEX
#  fi
  
on_failure: echo "Showing current directory contents" && ls -la
